# Generated by Django 4.2.7 on 2023-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hikepal", "0002_alter_activity_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="experience_gain",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trail",
            name="distance",
            field=models.FloatField(),
        ),
    ]
